#!/bin/bash
# Production build script for SPD Learn documentation
# This script optimizes the build for deployment with smaller size and better SEO
set -e

echo "=========================================="
echo "SPD Learn Documentation Production Build"
echo "=========================================="

# Navigate to docs directory
cd "$(dirname "$0")"

# Clean previous build
echo "Cleaning previous build..."
rm -rf build/

# Build with production settings (warnings as errors)
echo "Building documentation..."
SPHINXOPTS="-W --keep-going" make html

# Post-build optimization
echo "Optimizing images..."
if command -v optipng &> /dev/null; then
    find build/html -name "*.png" -size +100k -exec optipng -o5 -quiet {} \; 2>/dev/null || true
    echo "  PNG optimization complete"
else
    echo "  optipng not found - skipping PNG optimization"
    echo "  Install with: brew install optipng (macOS) or apt install optipng (Linux)"
fi

# Remove unnecessary source files (if any were generated)
echo "Cleaning up unnecessary files..."
rm -rf build/html/_sources/generated/auto_examples/visualizations/ 2>/dev/null || true

# Copy robots.txt to build output
if [ -f "source/_static/robots.txt" ]; then
    cp source/_static/robots.txt build/html/
    echo "  robots.txt copied"
fi

# Sitemap is generated automatically by sphinx-sitemap extension
echo "Sitemap generated by sphinx-sitemap extension"

# Report final size
echo ""
echo "=========================================="
echo "Build complete!"
echo "=========================================="
echo "Output directory: build/html/"
echo "Size:"
du -sh build/html/
echo ""
echo "Largest files:"
find build/html -type f -size +1M -exec ls -lh {} \; 2>/dev/null | sort -k5 -h | tail -10
